In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [ ]:
#untuk upload file dataset
#upload dilakukan secara manual
from google.colab import files
uploaded = files.upload()

#Memanggil file dataset yang digunakan
iris = pd.read_csv('Iris.csv')
iris.head()

Saving Iris.csv to Iris.csv


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df_iris = pd.read_csv('Iris.csv')

In [ ]:
df_iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [ ]:
df_iris.size

900

In [ ]:
df_iris.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
# menetapkan variable fitur dan target
x = df_iris.drop(['Species'], axis=1)

y = df_iris['Species']

In [ ]:
# membagi data menjadi data training dan data testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.5, random_state = 1)

In [ ]:
#cek bentuk data
x_train.shape, x_test.shape

((75, 5), (75, 5))

In [ ]:
cols = x_train.columns

In [ ]:
# mengaktifkan/memanggil/membuat fungsi klasifikasi naive bayes
modelnb = GaussianNB()

# memasukkan data training pada fungsi klasifikasi naive bayes
nbtrain = modelnb.fit(x_train, y_train)

# mengamati sampel setiap kelas
nbtrain.class_count_

array([26., 26., 23.])

In [ ]:
# menentukan hasil prediksi dari x_test
y_pred = nbtrain.predict(x_test)
y_pred

array(['Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa

In [ ]:
# melakukan pengujian untuk probabilitas x_test
nbtrain.predict_proba(x_test)

array([[1.00000000e+000, 3.49406362e-020, 1.31382269e-039],
       [2.96441220e-031, 9.99999997e-001, 3.33875990e-009],
       [3.09709921e-087, 9.99919557e-001, 8.04428703e-005],
       [1.00000000e+000, 2.22786251e-018, 6.47490172e-038],
       [1.09399052e-240, 3.65284136e-012, 1.00000000e+000],
       [3.46492570e-102, 9.99880182e-001, 1.19818235e-004],
       [1.15004004e-174, 5.79792405e-012, 1.00000000e+000],
       [1.00000000e+000, 1.55946025e-011, 2.11280165e-027],
       [1.00000000e+000, 5.94247561e-017, 6.00728385e-035],
       [8.99672485e-203, 1.80561306e-010, 1.00000000e+000],
       [2.36359046e-074, 9.99935378e-001, 6.46217576e-005],
       [1.00000000e+000, 5.27307842e-018, 2.42808034e-036],
       [1.44016743e-201, 4.92796211e-007, 9.99999507e-001],
       [3.00836075e-090, 9.99994529e-001, 5.47132787e-006],
       [3.76237210e-092, 9.99800532e-001, 1.99468040e-004],
       [1.00000000e+000, 1.13869568e-016, 3.24553415e-035],
       [1.08224788e-064, 9.99995179e-001

In [ ]:
confusion_matrix(y_test, y_pred)

array([[24,  0,  0],
       [ 0, 24,  0],
       [ 0,  0, 27]])

In [ ]:
# menampilkan tingkat akurasi klasifikasi menggunakan naive bayes dengan dataset iris plant
print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        24
Iris-versicolor       1.00      1.00      1.00        24
 Iris-virginica       1.00      1.00      1.00        27

       accuracy                           1.00        75
      macro avg       1.00      1.00      1.00        75
   weighted avg       1.00      1.00      1.00        75

