In [ ]:
!pip install ipython-autotime

%load_ext autotime

The autotime extension is already loaded. To reload it, use:
  %reload_ext autotime
time: 2.63 s


In [ ]:
# multi-class classification (one-vs-one) (menggunakan SVM)
# melakukan import library yang diperlukan
from sklearn.svm import SVC
from sklearn.utils import shuffle
from sklearn.metrics import confusion_matrix
from sklearn.multiclass import OneVsOneClassifier
import numpy as np
import pylab as pl
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
# melakukan import dataset 'Iris' dari library scikit-learn dataset
from sklearn import datasets
# Memanggil dataset
iris = datasets.load_iris()

time: 6.7 ms


In [ ]:
#Cetak 13 nama fitur
print("Features: ", iris.feature_names)

#Cetak label jenis 
print("Labels: ", iris.target_names)

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']
time: 3.42 ms


In [ ]:
# Menampilkan dimensi data (baris, kolom)
iris.data.shape

(150, 4)

time: 5.04 ms


In [ ]:
# menampilkan 10 data pertama dari variabel 'features'
print(iris.data[0:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
time: 4.11 ms


In [ ]:
# Cetak label data
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
time: 2.54 ms


In [ ]:
# Import fungsi train_test_split
from sklearn.model_selection import train_test_split

# Membagi dataset menjadi training set dan test set
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.25,random_state=123) # 75% training and 25% test

time: 6.99 ms


In [ ]:
# Membuat svm Classifier (tidak jadi dipakai)
# clf = svm.SVC(kernel='linear') # Linear Kernel

time: 721 µs


In [ ]:
# mendefinisikan model OvO menggunakan SVM
model = SVC(decision_function_shape='ovo')
# mendeklarasikan model OneVsOne
ovo = OneVsOneClassifier(model)
# fit model
ovo.fit(X_train, y_train)
# Memprediksikan respons untuk test dataset
y_pred = ovo.predict(X_test)

time: 12.5 ms


In [ ]:
y_pred

array([1, 2, 2, 1, 0, 1, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 2, 0])

time: 5.34 ms


In [ ]:
y_test

array([1, 2, 2, 1, 0, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2,
       0, 2, 0, 0, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 2, 0])

time: 3.52 ms


In [ ]:
# Menampilkan confusion matriks untuk mengetahui kesalahan dalam pengklasifikasian data
confusion_matrix(y_test, y_pred)

array([[16,  0,  0],
       [ 0,  8,  0],
       [ 0,  3, 11]])

time: 4.61 ms


In [ ]:
# Menampilkan tingkat akurasi dari pengklasifikasian    menggunakan algoritma SVM untuk metode OneVsOne
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.73      1.00      0.84         8
           2       1.00      0.79      0.88        14

    accuracy                           0.92        38
   macro avg       0.91      0.93      0.91        38
weighted avg       0.94      0.92      0.92        38

time: 11 ms
